services:
  polybot_farm:
    build: .
    container_name: polybot_farm
    command: ./farm_bot
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/storage
    restart: unless-stopped

  polybot_real:
    build: .
    container_name: polybot_real
    command: ./real_bot
    ports:
      - "9090:9090"
    env_file:
      - .env
    volumes:
      - ./data:/app/storage
    restart: unless-stopped
