version: '3.8'

services:
  scanner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polymarket-btc-v03-scanner
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./output:/app/output
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: polymarket-btc-v03-be
    restart: always
    ports:
      - "8083:8083"
    volumes:
      - ./data:/app/data